apiVersion: v1
kind: ConfigMap
metadata:
  name: my-env
data:
  DB_USERNAME: "postgres"
  DB_NAME: "postgres"
  DB_HOST: "postgresql-service"
  DB_PORT: "5432"
---
apiVersion: v1
kind: Secret
metadata:
  name: my-secret
type: Opaque
data:
  DB_PASSWORD: bXlwYXNzd29yZA==